version: '3'
services: 
    express-app:
        build: .
        ports: 
            - ${PORT}:${PORT}
        depends_on: 
            - postgres
        environment: 
            - PORT=${PORT}
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 10
                window: 120s
    postgres:
        build: ./database/
        ports: 
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
            POSTGRES_DB: ${POSTGRES_DB}
        
