version: '3'
services: 
    express-app-image:
        build: .
        command: npm run start
        volumes: 
            - ./src:/usr/app/src
            - /usr/app/node_modules
        ports: 
            - ${PORT}:${PORT}
        depends_on: 
            - postgres-image
        environment: 
              PORT: ${PORT}
        restart: on-failure
        networks:
            - my-network
    postgres-image:
        image: postgres-image
        build: ./database/
        ports: 
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - ./database:/var/lib/postgresql/data
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
            POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
            POSTGRES_PORT: ${POSTGRES_PORT}
            PGDATA: ${PGDATA}
        restart: on-failure
        networks:
            - my-network

networks: 
    my-network:
        driver: bridge
